### ISSUE TITLE
EIP-4788 Spec Change Tracker

### ISSUE THREAD

**Issue by spencer-tb** [ethereum/execution-spec-tests#150]
Spec: https://eips.ethereum.org/EIPS/eip-4788

```[tasklist]
### To change in tests.
- [x] Update to Precompile Address: https://github.com/ethereum/EIPs/pull/7173
- [x] Bound state growth of beacon root contract: https://github.com/ethereum/EIPs/pull/7126/files
- [x] Bound precompile storage: https://github.com/ethereum/EIPs/pull/7178/files
```

**Comment by spencer-tb** [comment]
Superseded by #236
