### ISSUE TITLE
Remaining EIP-1153 Vectors

### ISSUE THREAD

**Issue by marioevz** [ethereum/execution-spec-tests#291]
```[tasklist]
### Tasks
- [x] Re-entrancy test where we TSTORE with CALL and TLOAD->RETURN with STATICCALL.
- [x] Fix xfail: test_reentrant_call[fork=Cancun-invalid_undoes_tstorage_after_successful_call] XFAIL
- [x] Add TSTORE+Selfdestruct tests
```
