### ISSUE TITLE
Prague Tracker

### ISSUE THREAD

**Issue by marioevz** [ethereum/execution-spec-tests#498]
```[tasklist]
### EIPs
- [x] [EIP-2537: Precompile for BLS12-381 curve operations](https://eips.ethereum.org/EIPS/eip-2537)
- [x] [EIP-2935: Save historical block hashes in state](https://eips.ethereum.org/EIPS/eip-2935)
- [x] [EIP-3074: AUTH and AUTHCALL opcodes](https://eips.ethereum.org/EIPS/eip-3074)
- [x] [EIP-6110: Supply validator deposits on chain](https://eips.ethereum.org/EIPS/eip-6110)
- [x] [EIP-7002: Execution layer triggerable exits](https://eips.ethereum.org/EIPS/eip-7002)
- [x] [EIP-7251: Increase the MAX_EFFECTIVE_BALANCE](https://eips.ethereum.org/EIPS/eip-7251) *
```

* Impact depends on whether the EIP includes modifications to the Execution layer or not.

**Comment by marioevz** [comment]
Devops Devnet-0 Specs: https://notes.ethereum.org/@ethpandaops/pectra-devnet-0

**Comment by spencer-tb** [comment]
CIFO #1299
