### ISSUE TITLE
EOF Tracker

### ISSUE THREAD

**Issue by marioevz** [ethereum/execution-spec-tests#500]
```[tasklist]
### Tasks
- [x] Create a test spec type for the EOF container fixture format ([Done](https://github.com/ethereum/execution-spec-tests/commit/0022b4d94e3c91513e1b73090732f6e3b348953b)) 
- [ ] Update exceptions.py to add the existing EOF exceptions to the [Enum](https://github.com/ethereum/execution-spec-tests/blob/760a67e03baa23d782c9c8762c13ca6089920bda/src/ethereum_test_tools/exceptions/exceptions.py#L167)
- [ ] Add automatic BlockchainTest and BlockchainHiveTest generation to the [`EOFTest`](https://github.com/ethereum/execution-spec-tests/blob/760a67e03baa23d782c9c8762c13ca6089920bda/src/ethereum_test_tools/spec/eof/eof_test.py#L16) spec.
- [ ] Update or create a new class to be able to generate and parametrize EOF containers according to the latest spec
- [ ] Port [EIP3540](https://github.com/ethereum/tests/tree/develop/src/EOFTestsFiller/EIP3540)
- [ ] Port [EIP3670](https://github.com/ethereum/tests/tree/develop/src/EOFTestsFiller/EIP3670)
- [ ] Port [EIP4200](https://github.com/ethereum/tests/tree/develop/src/EOFTestsFiller/EIP4200)
- [ ] Port [EIP4750](https://github.com/ethereum/tests/tree/develop/src/EOFTestsFiller/EIP4750)
- [ ] Port [EIP5450](https://github.com/ethereum/tests/tree/develop/src/EOFTestsFiller/EIP5450)
```

**Comment by gumb0** [comment]
To summarize the current status of our existing tests:

1. https://github.com/ethereum/tests/tree/develop/src/EIPTestsFiller/StateTests/stEOF/stEIP3540
https://github.com/ethereum/tests/tree/develop/src/EIPTestsFiller/StateTests/stEOF/stEIP4200
https://github.com/ethereum/tests/tree/develop/src/EIPTestsFiller/StateTests/stEOF/stEIP4750
https://github.com/ethereum/tests/tree/develop/src/EIPTestsFiller/StateTests/stEOF/stEIP5450
 - These tests were written a while ago for Shanghai version of the spec, after that they were mostly only updated to keep them compatible with the later changes. We removed all tests testing EOF validation aspect and made validation tests from them (see below). I wouldn't expect these tests to cover all complexities of current version of EIPs-3540, 4200, 4750, 5450 (but they do pass with current spec)

2. EOF validation tests https://github.com/ethereum/tests/tree/develop/src/EOFTestsFiller
  - These are partially hand-written (`EIP*` folders, also `ori), and partially generated from evmone unit tests, which @winsvega merged recently as Copier tests (`ef*` folders). I expect these test to cover almost all aspects of validation reasonably well.

3. https://github.com/ethereum/tests/pull/1324
 - State tests generated from evmone tests, these mostly test various aspects of contract creation (`EOFCREATE`, `TXCREATE`, InitcodeTransactions), new `EXTCALL*` instructions and some related execution aspects.

**Comment by felix314159** [comment]
EOF
