### ISSUE TITLE
feat(fw,tests): prague devnet-5 tracker

### ISSUE THREAD

**Issue by spencer-tb** [ethereum/execution-spec-tests#956]
### prague-devnet-5 Testing Tasks Tracker

[@ethpandaops/prague-devnet-5 specs](https://notes.ethereum.org/@ethpandaops/pectra-devnet-5)

Devnet-5 Date Tentative: 06/12/24 (Friday)

Testing release aim for 05/12/24 (ACD)

```[tasklist]
#### To merge in EEST/EELS
- [ ] ethereum/execution-specs#1045 -
- [ ] https://github.com/ethereum/execution-spec-tests/pull/931 - 
- [ ] ethereum/execution-spec-tests#986 -
- [ ] https://github.com/ethereum/execution-spec-tests/pull/994 - 
- [ ] ethereum/execution-spec-tests#984 -
- [ ] ethereum/execution-spec-tests#990 -
- [ ] ethereum/execution-spec-tests#933 -
- [ ] ethereum/execution-spec-tests#990 -
- [ ] ethereum/execution-specs#1042 -
- [ ] ethereum/execution-spec-tests#981 -
- [ ] ethereum/execution-spec-tests#996 -
- [ ] ethereum/execution-spec-tests#998 -
```

```[tasklist]
#### Included in devnet-5
- [ ] ethereum/EIPs#9007 - #931
- [ ] ethereum/EIPs#8822 - #9
- [ ] ethereum/execution-apis#574 - #994
- [ ] ethereum/EIPs#8969 - #984
- [x] ethereum/EIPs#8989 - #990
- [x] ethereum/execution-apis#599 - #990
```
```[tasklist]
#### Update 7702 System Contract
- [x] ethereum/EIPs#9040 - #990
- [x] ethereum/EIPs#9024 - #990
- [x] ethereum/EIPs#9025 - #990
```

```[tasklist]
#### Still TBD for devnet-5
```

```[tasklist]
#### EELS PRs
- [ ] ethereum/execution-specs#1042 -
- [ ] ethereum/execution-specs#1046
- [ ] ethereum/execution-specs#1045
- [x] ethereum/execution-specs#1041 -
```
