### ISSUE TITLE
tracker(static tests): port ethereum/tests test cases

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-spec-tests#972]
This is a top-level issue for tracking the manual porting of ethereum/tests test cases to execution-spec-tests:

> **Contributions to manually port individual test cases are very welcome!**

**If you're already familiar with ethereum/tests and execution-spec-tests, jump to the issue tracker below!**

#### Background
[ethereum/tests](https://github.com/ethereum/tests) was the repository used to define EVM test cases from [Frontier](https://ethereum.org/en/history/#frontier) up to and including [The Merge](https://ethereum.org/en/history/#paris). The test cases are defined as YAML (and sometimes JSON) files in the [./src/ sub-directory](https://github.com/ethereum/tests/tree/develop/src) and the JSON "test fixtures" (fully-populated tests that can be executed against clients) are generated using [ethereum/retesteth](https://github.com/ethereum/retesteth). These JSON artifacts are regenerated when required and added to the repository, for example, in the [./GeneralStateTests/ sub-directory](https://github.com/ethereum/tests/tree/develop/GeneralStateTests).

From [Shanghai](https://ethereum.org/en/history/#shapella) on, new test cases (in particular for new features included in hard-forks) have been defined in Python in this repository (execution-spec-tests). The existing test cases are still important to execute against clients, however, and porting ethereum/tests to execution-spec-tests ensures that the test cases can be continually maintained and filled (generated) for newer forks. It also has the advantage that client teams will only need to obtain test fixture releases from one source.

#### Automated Port to Python
Although there will be an effort to automate ("transpile") the remaining test cases from YAML (respectively JSON) to Python; contributions to manually port individual test cases can be very beneficial and are welcome! 

The benefits of manual porting are:
1. Reduce the number of test cases by combing multiple YAML (resp. JSON) test cases in one Python test function (via parametrization).
2. Potentially improve coverage by parametrizing the Python version.
3. Code/docstrings are likely higher quality than an automated conversion.
4. The test can be better [organized within the `./tests` folder](https://ethereum.github.io/execution-spec-tests/main/writing_tests/adding_a_new_test/) in execution-spec-tests by the fork and the EIP in which the functionality was introduced.

#### Process
1. Pick a single or a set of YAML test cases in ethereum/tests to port and create an issue in this repository - optional, but definitely recommended if porting tests from the tracker below to avoid duplicate work.
2. Create a PR with the ported tests:
    a. Add the list of ported YAML files to [converted-ethereum-tests.txt](https://github.com/ethereum/execution-spec-tests/blob/1b30c336eae6b0746ea4db441ac74406f2fb2322/converted-ethereum-tests.txt).
    b. If the tests can't currently be filled, please explain the issue (feel free to also [open a Discussion](https://github.com/ethereum/execution-spec-tests/discussions/new?category=general)).

#### Help with ethereum/tests

The test formats are described in the [ethereum/tests online docs](https://ethereum-tests.readthedocs.io/en/latest/blockchain-ref.html). Note that state filler test cases in YAML can be parametrized, see the [docs here](https://ethereum-tests.readthedocs.io/en/latest/test_filler/state_filler.html#the-indexes).

#### Hints to Get Started with ethereum/execution-spec-tests

0. Start here: [Getting Started → Installation](https://ethereum.github.io/execution-spec-tests/main/getting_started/installation/).
1. Use `uv run et make test` to create a template test module (currently a WIP in ethereum/execution-spec-tests#950).
2. Where to put the test? See how tests are organized in [Writing Tests → Adding a New Test](https://ethereum.github.io/execution-spec-tests/main/writing_tests/adding_a_new_test/).
3. State vs Blockchain test? If in doubt try to write a state test, see [Writing Tests → Types of Tests → Deciding on a Test Type](https://ethereum.github.io/execution-spec-tests/main/writing_tests/types_of_tests/#deciding-on-a-test-type).
4. Tests are filled via EELS by default (no further installation necessary; it's a Python dependency and got installed in Step 0), see [Filling  → Getting Started](https://ethereum.github.io/execution-spec-tests/main/filling_tests/getting_started/).
5. Parametrizing test functions is encouraged, see [Writing Tests → Writing a New Test → Parametrizing Tests](https://ethereum.github.io/execution-spec-tests/main/writing_tests/writing_a_new_test/#parametrizing-tests).
6. The Opcode mini-lang defined in this repository is the preferred way to define bytecode in tests (if feasible). For a very simple example, see [`test_chainid()`](https://github.com/ethereum/execution-spec-tests/blob/85393456e75f5f3b476cb5e61c35d48172f9d543/tests/istanbul/eip1344_chainid/test_chainid.py#L28) - there are other examples in the tests.

Feel free to reach out for help or guidance in the Ethereum R&D discord or via DM; see [Getting Help](https://ethereum.github.io/execution-spec-tests/main/getting_started/getting_help/) in the docs.

```[tasklist]
### Test Cases
- [ ] Add test cases for any single opcode (porting an entire test case from ethereum/tests can be overwhelming; instead add your own test cases for a single opcode from https://www.evm.codes/).
- [x] [src/GeneralStateTestsFiller/VMTests/vmTests](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/VMTests/vmTests) - swapFiller.yml - WIP: ethereum/execution-spec-tests#1012
- [x] [src/GeneralStateTestsFiller/VMTests/vmTests](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/VMTests/vmTests) - dupFiller.yml.
- [x] [src/GeneralStateTestsFiller/VMTests/vmTests](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/VMTests/vmTests) - pushFiller.yml - WIP: ethereum/execution-spec-tests#974
- [ ] [src/GeneralStateTestsFiller/VMTests/vmTests](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/VMTests/vmTests) (Note: DUP already ported).
- [ ] [src/GeneralStateTestsFiller/stLogTests/](https://github.com/ethereum/tests/tree/4f65a0a7cbecf4442415c226c65e089acaaf6a8b/src/GeneralStateTestsFiller/stLogTests).
- [ ] [src/GeneralStateTestsFiller/stRandom](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stRandom) and [src/GeneralStateTestsFiller/stRandom2](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stRandom2) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stZeroKnowledge](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stZeroKnowledge) and [src/GeneralStateTestsFiller/stZeroKnowledge2](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stZeroKnowledge2) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stPreCompiledContracts1](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stPreCompiledContracts1) and [src/GeneralStateTestsFiller/stPreCompiledContracts2](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stPreCompiledContracts2) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stQuadraticComplexityTest](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stQuadraticComplexityTest) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stSStoreTest](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stSStoreTest) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stTimeConsuming](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stTimeConsuming) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stWalletTest](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stWalletTest) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stCallCodes](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stCallCodes), [src/GeneralStateTestsFiller/stCallDelegateCodesCallCodeHomestead](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stCallDelegateCodesCallCodeHomestead) and [src/GeneralStateTestsFiller/stCallDelegateCodesHomestead](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stCallDelegateCodesHomestead) (see ethereum/execution-specs#1505 for details)
- [ ] [src/GeneralStateTestsFiller/stEIP150singleCodeGasPrices](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stEIP150singleCodeGasPrices) (see ethereum/execution-specs#1505 for details)
```

#### Some Examples of Ported Tests

| ethereum/tests | ethereum/execution-spec-tests|
|---------------------|------------------------------------------|
| [src/GeneralStateTestsFiller/VMTests/vmTests/dupFiller.yml](https://github.com/ethereum/tests/blob/4f65a0a7cbecf4442415c226c65e089acaaf6a8b/src/GeneralStateTestsFiller/VMTests/vmTests/dupFiller.yml) | [tests/frontier/opcodes/test_dup.py](https://github.com/ethereum/execution-spec-tests/blob/1b30c336eae6b0746ea4db441ac74406f2fb2322/tests/frontier/opcodes/test_dup.py) |
| [GeneralStateTests/stCreate2/call_outsize_then_create2_successful_then_returndatasize.json](https://github.com/ethereum/tests/blob/4f65a0a7cbecf4442415c226c65e089acaaf6a8b/src/GeneralStateTestsFiller/stCreate2/call_outsize_then_create2_successful_then_returndatasizeFiller.json), [GeneralStateTests/stCreate2/call_then_create2_successful_then_returndatasize.json](https://github.com/ethereum/tests/blob/4f65a0a7cbecf4442415c226c65e089acaaf6a8b/src/GeneralStateTestsFiller/stCreate2/call_then_create2_successful_then_returndatasizeFiller.json)| [tests/constantinople/eip1014_create2/test_create_returndata.py](https://github.com/ethereum/execution-spec-tests/blob/1b30c336eae6b0746ea4db441ac74406f2fb2322/tests/constantinople/eip1014_create2/test_create_returndata.py) |

**Comment by pacrob** [comment]
I'll take porting `swapFiller.yml` if nobody's working on it yet.

**Comment by bomanaps** [comment]
Please can I take on swapFiller.yml? @danceratopz

**Comment by danceratopz** [comment]
> Please can I take on swapFiller.yml? @danceratopz

Yes, @bomanaps! Please make an issue when you get started and I can link it in the tracker here to avoid anyone else working on it :)

**Comment by Giszter** [comment]
Hi @winsvega Sorry I haven't written in so long, but I got sick and then Christmas..As I see from docs the best idea will be to start with tag: 'good first issue'. In this case can I take for example:  [https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stEIP150singleCodeGasPrices](url) ? Or maybe there is something more important ?
ps. Happy New Year ;)

**Comment by winsvega** [comment]
That seems to only check the gas price of individual opcodes. That should be already covered in pyspec.

Take a look at https://github.com/ethereum/execution-spec-tests/issues/1016

**Comment by Giszter** [comment]
So maybe this one [stWalletTest](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stWalletTest)
?

**Comment by Giszter** [comment]
> That seems to only check the gas price of individual opcodes. That should be already covered in pyspec.
> 
> Take a look at #1016

So maybe this one [stWalletTest](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stWalletTest)
?

**Comment by reedsa** [comment]
@danceratopz @winsvega If the Zero Knowledge and/or Precompiled Contracts are available, I'll dig into those.

**Comment by winsvega** [comment]
> > That seems to only check the gas price of individual opcodes. That should be already covered in pyspec.
> > 
> > Take a look at #1016
> 
> So maybe this one [stWalletTest](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stWalletTest)
> ?

stWallet test is not an evm test. This is a legacy test for a smart contract, I just kept it as a legacy, and it probably doesn't cover anything evm related.

**Comment by Giszter** [comment]
@winsvega  this one can be ok ? [stWalletTest](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stWalletTest) ? it is from  https://github.com/ethereum/execution-spec-tests/issues/1016

**Comment by Giszter** [comment]
hm so in this case @winsvega can you suggest  which one I can take? maybe it will be easier to choose correct one ;)

**Comment by winsvega** [comment]
StRandom

**Comment by winsvega** [comment]
- [ ]  stCreateTest/CREATE_ContractSuicideDuringInit_ThenStoreThenReturnFiller.json,
        stCreateTest/CREATE_ContractSuicideDuringInit_WithValueFiller.json,
        stCreateTest/CREATE_ContractSuicideDuringInit_WithValueToItselfFiller.json,
        stCreateTest/CREATE_ContractSuicideDuringInitFiller.json
        https://github.com/ethereum/execution-spec-tests/pull/1871
- [ ] stCreateTest/CREATE_AcreateB_BSuicide_BStoreFiller.json https://github.com/ethereum/execution-spec-tests/pull/1867
