### ISSUE TITLE
✨(et): make `et make test` great

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-spec-tests#973]
The `uv run et make test` command is an interactive CLI that helps a user create a new test module and function as a starting point to creating a new test. See https://ethereum.github.io/execution-spec-tests/main/writing_tests/.

```[tasklist]
### Tasks
- [x] [✨ (cli): Add support for interactive CLI input | execution-spec-tests#945](https://github.com/ethereum/execution-spec-tests/issues/945)
- [x] [✨(testinit): add a simple (interactive?) cli that creates a new test module skeleton | execution-spec-tests#926](https://github.com/ethereum/execution-spec-tests/issues/926)
- [ ] [✨(testinit): add support for parametrized tests and different test types | execution-spec-tests#927](https://github.com/ethereum/execution-spec-tests/issues/927)
- [x] [✨(make): Add support for make package | execution-spec-tests#946](https://github.com/ethereum/execution-spec-tests/issues/946)
```
